# Generated by Django 5.0 on 2024-03-24 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Имя пользователя')),
                ('email', models.CharField(max_length=250, verbose_name='Электронная почта')),
                ('password', models.CharField(max_length=250, verbose_name='Пароль')),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата регистрации')),
                ('last_login', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата последнего входа')),
            ],
            options={
                'verbose_name': 'Пользователя',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_hash_algorithm', models.CharField(max_length=50, verbose_name='Алгоритм хеширования')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройки пользователей',
                'verbose_name_plural': 'Настройки пользователей',
                'db_table': 'settings',
            },
        ),
    ]
