# Generated by Django 5.0 on 2024-02-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='preferred_hash_algorithm',
            field=models.CharField(max_length=50, verbose_name='Алгоритм хеширования'),
        ),
    ]
