# Generated by Django 5.0 on 2024-04-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email_alter_user_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='totp_login',
            field=models.BooleanField(default=False, verbose_name='2FA'),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='2FA секретный ключ'),
        ),
    ]
