###Obtain Token

POST http://127.0.0.1:8000/user/api/token/ HTTP/1.1
content-type: application/json

{
    "username": "user1",
    "password": "kav18032001"
}

###Send TOTP code
POST http://127.0.0.1:8000/user/api/totp/verify/ HTTP/1.1
content-type: application/json

{
    "username": "user1",
    "password": "kav18032001",
    "totp_code": "415509"
}

###TOTP Setup
POST http://127.0.0.1:8000/user/api/totp/setup/ HTTP/1.1
content-type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzEyMjI3NDIwLCJpYXQiOjE3MTIyMjY4MjAsImp0aSI6IjQ1YmI2ZTZiYTQyODRjZGZiOTZiMTY1Y2IxNGE1Yjg1IiwidXNlcl9pZCI6MjIsInVzZXJuYW1lIjoidXNlcjEifQ.hSpV5rhkU7uWRxSmMLvA91ThzDTtZ303CXOWyrjvYPs

{

}

###GET Records

GET http://127.0.0.1:8000/vault/api/records
content-type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzEyMTM3MzAzLCJpYXQiOjE3MTIxMzY3MDMsImp0aSI6IjZlOWJlNmIxOGQzYjRmYTJiMjc2YTA3MDAzNzJlNjZmIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJyb290In0.fVrQYrSAzmyGtiWVKsQAKL7MZhzf055kGLac5uJpBL8

{

}

###Add record
POST http://127.0.0.1:8000/vault/api/records/
content-type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzEyMTM2NDg2LCJpYXQiOjE3MTIxMzU4ODYsImp0aSI6IjJlZTkzOWQ5MTQ2YzRmMGU4MzUyMzc5YjY0OWU4OTIyIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJyb290In0.NVy0k2vPlsbwXzeplh-0XVzwFzUxikILumk-TE0lxx4

{
    "app_name": "test",
    "username": "root"
}

###Change record
PUT http://127.0.0.1:8000/vault/api/records/18/
content-type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzEyMTM2NDg2LCJpYXQiOjE3MTIxMzU4ODYsImp0aSI6IjJlZTkzOWQ5MTQ2YzRmMGU4MzUyMzc5YjY0OWU4OTIyIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJyb290In0.NVy0k2vPlsbwXzeplh-0XVzwFzUxikILumk-TE0lxx4

{
    "app_name": "tester1",
    "username": "root"
}

###Delete record
DELETE http://127.0.0.1:8000/vault/api/records/18/
content-type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzEyMTM2NDg2LCJpYXQiOjE3MTIxMzU4ODYsImp0aSI6IjJlZTkzOWQ5MTQ2YzRmMGU4MzUyMzc5YjY0OWU4OTIyIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJyb290In0.NVy0k2vPlsbwXzeplh-0XVzwFzUxikILumk-TE0lxx4

{

}

###GET categories
GET http://127.0.0.1:8000/vault/api/categories/
content-type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzEyMTM3NzgzLCJpYXQiOjE3MTIxMzcxODMsImp0aSI6Ijg4ZjEzYjM1MGM1YTQ3MWJiMzhiZDhhMWIxM2M5MTFiIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJyb290In0.x1orJ-lfG8EFKv7gOVarqkmkl3dQZ1Pqh_qYgmB6K94

{

}

