###Obtain Token

POST http://127.0.0.1:8000/user/api/login/ HTTP/1.1
content-type: application/json

{
    "username": "root",
    "password": "root"
}

###Send TOTP code
POST http://127.0.0.1:8000/user/api/login/ HTTP/1.1
content-type: application/json

{
    "username": "root",
    "password": "root",
    "totp_code": "826110"
}


###TOTP Setup
POST http://127.0.0.1:8000/user/api/totp/setup/ HTTP/1.1
content-type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE1MTc3ODMzLCJpYXQiOjE3MTUxNzcyMzMsImp0aSI6IjRlZjEyYTcxZmNmMzQ0MTNhMDBlMzJkYzM5N2ZjYzJiIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJyb290In0.o17nGOHdyvCDpXhMx294kfoPKDPLSb7ybkoqk1bN8qg

{

}

###GET Records

GET http://127.0.0.1:8000/vault/api/records/
content-type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE3NTcwMTA5LCJpYXQiOjE3MTc1Njk1MDIsImp0aSI6IjNmZTgzYjFlODNiMDRjZTk5YmM1ODhhNjZmYTAxODgwIiwidXNlcl9pZCI6MjIsInVzZXJuYW1lIjoicm9vdCJ9.PPR_Y-HJkQJAHfzmDkFugteLs5A-NHuFnor4lwSPnOM

{

}

###Add record
POST http://127.0.0.1:8000/vault/api/records/
content-type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE3NTcwMTA5LCJpYXQiOjE3MTc1Njk1MDIsImp0aSI6IjNmZTgzYjFlODNiMDRjZTk5YmM1ODhhNjZmYTAxODgwIiwidXNlcl9pZCI6MjIsInVzZXJuYW1lIjoicm9vdCJ9.PPR_Y-HJkQJAHfzmDkFugteLs5A-NHuFnor4lwSPnOM

{"app_name":"1234","category":"","username":"2","password":"2","url":""}

###Change record
    PUT http://127.0.0.1:8000/vault/api/records/125/
content-type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE3NTcwMTA5LCJpYXQiOjE3MTc1Njk1MDIsImp0aSI6IjNmZTgzYjFlODNiMDRjZTk5YmM1ODhhNjZmYTAxODgwIiwidXNlcl9pZCI6MjIsInVzZXJuYW1lIjoicm9vdCJ9.PPR_Y-HJkQJAHfzmDkFugteLs5A-NHuFnor4lwSPnOM

{
    "app_name": "tester1",
    "username": "root",
    "totp_secret": "123"
    
}

###Delete record
DELETE http://127.0.0.1:8000/vault/api/records/48/
content-type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE3MDk1MjA4LCJpYXQiOjE3MTcwOTQzNjIsImp0aSI6IjZiNmFmN2M1NjJiZDQyMjdiZmE0Mjc3ODNjZDMxOTkzIiwidXNlcl9pZCI6MjIsInVzZXJuYW1lIjoicm9vdCJ9._QmemZM1HcbD5shpdNuZY45kLQOK49zgSP6e-AOMWGk

{

}

###GET categories
GET http://127.0.0.1:8000/vault/api/categories/
content-type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE3MTU5NDc3LCJpYXQiOjE3MTcxNTg4NzQsImp0aSI6ImJiNmRiZTEyYzM2ZTRiOGM5NWZhNDQxZGYwOTE5MDk3IiwidXNlcl9pZCI6MjIsInVzZXJuYW1lIjoicm9vdCJ9.wI5OWe0SdHuqmIqiV4ewNgl7cZNIMEWG-MZrtwZhxb8

{

}


###ADD categories
POST http://127.0.0.1:8000/vault/api/categories/
content-type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE3MTU5NDc3LCJpYXQiOjE3MTcxNTg4NzQsImp0aSI6ImJiNmRiZTEyYzM2ZTRiOGM5NWZhNDQxZGYwOTE5MDk3IiwidXNlcl9pZCI6MjIsInVzZXJuYW1lIjoicm9vdCJ9.wI5OWe0SdHuqmIqiV4ewNgl7cZNIMEWG-MZrtwZhxb8

{
    "name": "category3"
}

