# Generated by Django 5.0 on 2024-01-17 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
                'db_table': 'category',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Passwords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, null=True, verbose_name='Имя пользователя')),
                ('password', models.CharField(max_length=300, null=True, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Пароль',
                'verbose_name_plural': 'Пароли',
                'db_table': 'password',
            },
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=150, verbose_name='Название приложения')),
                ('urls', models.JSONField(default=dict, max_length=500, null=True, verbose_name='Адреса')),
                ('notes', models.TextField(null=True, verbose_name='Заметки')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('lastmodified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата последнего изменения')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vault.categories', verbose_name='Категория')),
                ('records', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vault.passwords', verbose_name='Сохраненные пароли')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'db_table': 'record',
            },
        ),
    ]
