# Generated by Django 5.0 on 2024-01-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='favicons'),
        ),
    ]
