# Generated by Django 5.0 on 2024-05-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='password',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='records',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя пользователя'),
        ),
    ]
