# Generated by Django 5.0 on 2024-01-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_records_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='favicon_images'),
        ),
    ]
