# Generated by Django 5.0 on 2024-02-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_alter_categories_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='app_name',
            field=models.BinaryField(editable=True, max_length=300, verbose_name='Название приложения'),
        ),
    ]
