# Generated by Django 5.0 on 2024-06-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_alter_records_password_alter_records_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='2FA секретный ключ'),
        ),
    ]
