# Generated by Django 5.0 on 2024-02-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_alter_records_app_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='app_name',
            field=models.CharField(max_length=150, verbose_name='Название приложения'),
        ),
    ]
