# Generated by Django 5.0 on 2024-06-05 06:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_records_totp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Поле должно содержать только буквы латинского алфавита.')], verbose_name='2FA секретный ключ'),
        ),
    ]
