# Generated by Django 5.0 on 2024-01-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0004_alter_records_category_alter_records_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwords',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Основной аккаунт'),
        ),
        migrations.AlterField(
            model_name='records',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='favicon_images', verbose_name='Иконка приложения'),
        ),
    ]
