# Generated by Django 5.0 on 2024-02-01 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0005_passwords_is_main_alter_records_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='records',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vault.passwords', verbose_name='Сохраненные пароли'),
        ),
        migrations.AlterField(
            model_name='records',
            name='urls',
            field=models.JSONField(blank=True, default=dict, max_length=500, null=True, verbose_name='Адреса'),
        ),
    ]
